### ISSUE TITLE
Installing Error: cannot convert 'bool' to 'gzFile {aka gzFile_s*}'

### ISSUE THREAD

**Issue by ursueugen** [smilefreak/selectionTools#27]
Hello and thank you for creating this great workflow.

Could you suggest a solution to the following error that arises when running ./install.sh? Thank you

The error arises install.sh attempts to install vcftools (showing just relevant portion of log):

===============================

Installing VCF tools
make[1]: Entering directory '/home/dicer/Desktop/1000genome/code/selectionTools/vcftools_0.1.11/cpp'
g++ -c -O2 -D_FILE_OFFSET_BITS=64  vcftools.cpp -o vcftools.o
g++ -MM -O2 -D_FILE_OFFSET_BITS=64  vcftools.cpp > vcftools.d
g++ -c -O2 -D_FILE_OFFSET_BITS=64  bcf_file.cpp -o bcf_file.o
g++ -MM -O2 -D_FILE_OFFSET_BITS=64  bcf_file.cpp > bcf_file.d
g++ -c -O2 -D_FILE_OFFSET_BITS=64  vcf_file.cpp -o vcf_file.o
vcf_file.cpp: In constructor 'vcf_file::vcf_file()':
vcf_file.cpp:25:13: error: cannot convert 'bool' to 'gzFile {aka gzFile_s*}' in assignment
  gzvcf_in = false;
             ^~~~~
Makefile:53: recipe for target 'vcf_file.o' failed
make[1]: *** [vcf_file.o] Error 1
make[1]: Leaving directory '/home/dicer/Desktop/1000genome/code/selectionTools/vcftools_0.1.11/cpp'
/bin/sh: 2: cd: can't cd to perl
Makefile:24: recipe for target 'install' failed
make: *** [install] Error 2
error with make

===========================

As I searched for solutions, I found: https://stackoverflow.com/questions/42511519/cannot-convert-bool-to-gzfile-aka-gzfile-s

It didn't solve the issue. I performed the suggested modifications in /cpp/vcf_file.cpp but instead got other errors. 

I'm running a virtual linux machine with Oracle VM, Ubuntu 18.04.

**Comment by murraycadzow** [comment]
Hello,

The pipeline is getting rather old now and I haven't had time (nor am I likely to) to go through an update it with all the latest versions of the programs that it utilises.

To solve this particular issue the best way would be to install vcftools through apt-get (sudo apt-get install vcftools) and then comment out the vcftools install section of install.sh with '#' at the start each of the lines 53-57. 
Assuming no other problems arise during install then you'll need to update the config file (defaults.cfg) with the path to each of the vcftools programs we make use of (to get the path, use 'which' eg 'which vcftools'). 

thanks
Murray

**Comment by DeribaAbera1234** [comment]
This worked!
THANKS

**Comment by murraycadzow** [comment]
Great :)
