### ISSUE TITLE
Unable to perform task

### ISSUE THREAD

**Issue by devenderarora** [smilefreak/selectionTools#30]
I am trying to run on my snp data. I already phases vcf file using beagle nad converted the vcf file into biallelic using bcftools. Made map file by plink1.9 and hap file using bcftools. When I am running selscan it through an error saying:
Expected 18966793 loci in map file but found 17867577.
Any lead on how to fix this issue.
Thanks
Devender

**Comment by murraycadzow** [comment]
Hi,
If it's specifically issues getting your data to run with selscan check out https://github.com/szpiech/selscan which is the repo for that program. 

Thanks
Murray

**Comment by devenderarora** [comment]
I seriously have no idea how I redirect to selectionTools. Sorry for the inconvinence.
